"""empty message

Revision ID: 389f44de8e8a
Revises: 9f48f5be9a0f
Create Date: 2024-10-01 13:03:48.965757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389f44de8e8a'
down_revision = '9f48f5be9a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastevents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pastevents')
    # ### end Alembic commands ###
